from __future__ import annotations

SHADOW_READY = "SHADOW_READY"
READY_FOR_OBSERVATION_ONLY = "READY_FOR_OBSERVATION_ONLY"
NEEDS_GRADED_ROWS = "NEEDS_GRADED_ROWS"
NEEDS_MORE_COMPLETED_EVENTS = "NEEDS_MORE_COMPLETED_EVENTS"
NEEDS_OUTCOME_DIVERSITY = "NEEDS_OUTCOME_DIVERSITY"
NEEDS_PROBABILITY_FIELD = "NEEDS_PROBABILITY_FIELD"
NEEDS_SELECTION_FIELD = "NEEDS_SELECTION_FIELD"
NEEDS_RESULT_FIELD = "NEEDS_RESULT_FIELD"
NEEDS_EVENT_IDENTITY = "NEEDS_EVENT_IDENTITY"
DUPLICATE_HEAVY_SAMPLE = "DUPLICATE_HEAVY_SAMPLE"
DRIFT_REVIEW_NEEDED = "DRIFT_REVIEW_NEEDED"
CALIBRATION_REVIEW_NEEDED = "CALIBRATION_REVIEW_NEEDED"
